import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { griffin } from "@/fonts/font";

export const metadata: Metadata = {
  title: "Grace Snyder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${griffin.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
