export const imageArr = [
  {
    title: "Lowly Worm",
    url: "/assets/images/png/LowlyWorm.png",
    fullUrl: "/assets/images/jpg/LowlyWorm.jpg",
    cols: 3,
    rows: 3,
    itemIndex: 0,
  },
  {
    title: "Angler",
    url: "/assets/images/png/Angler.png",
    fullUrl: "/assets/images/jpg/Angler.jpg",
    cols: 6,
    rows: 3,
    itemIndex: 1,
  },
  {
    title: "Plump",
    url: "/assets/images/png/Plump.png",
    fullUrl: "/assets/images/jpg/Plump.jpg",
    cols: 3,
    rows: 3,
    itemIndex: 2,
  },
  {
    title: "Venus Fly Trap",
    url: "/assets/images/png/Venus.png",
    fullUrl: "/assets/images/jpg/Venus.jpg",
    cols: 5,
    rows: 3,
    itemIndex: 3,
  },
  {
    title: "Ode to Alouise",
    url: "/assets/images/png/Alouise.png",
    fullUrl: "/assets/images/jpg/Alouise.jpg",
    cols: 4,
    rows: 2,
    itemIndex: 4,
  },
  {
    title: "The Moon",
    url: "/assets/images/png/TheMoon.png",
    fullUrl: "/assets/images/jpg/TheMoon.jpg",
    cols: 3,
    rows: 3,
    itemIndex: 5,
  },
  {
    title: "blank",
    url: null,
    fullUrl: null,
    cols: 1,
    rows: 1,
  },
  {
    title: "The Sun",
    url: "/assets/images/png/TheSun.png",
    fullUrl: "/assets/images/jpg/TheSun.jpg",
    cols: 3,
    rows: 3,
    itemIndex: 6,
  },
  {
    title: "Swallowtail",
    url: "/assets/images/png/Swallowtail.png",
    fullUrl: "/assets/images/jpg/Swallowtail.jpg",
    cols: 6,
    rows: 4,
    itemIndex: 7,
  },
  {
    title: "Crocodile",
    url: "/assets/images/png/Crocodile.png",
    fullUrl: "/assets/images/jpg/Crocodile.jpg",
    cols: 3,
    rows: 3,
    itemIndex: 8,
  },
  {
    title: "Toadstool",
    url: "/assets/images/png/Toadstool.png",
    fullUrl: "/assets/images/jpg/Toadstool.jpg",
    cols: 3,
    rows: 3,
    itemIndex: 9,
  },
  {
    title: "Frozen Deer",
    url: "/assets/images/png/FrozenDeer.png",
    fullUrl: "/assets/images/jpg/FrozenDeer.jpg",
    cols: 3,
    rows: 2,
    itemIndex: 10,
  },

  {
    title: "Jackalope",
    url: "/assets/images/png/Jackalope.png",
    fullUrl: "/assets/images/jpg/Jackalope.jpg",
    cols: 4,
    rows: 3,
    itemIndex: 11,
  },

  {
    title: "This mouse has never seen the stars before",
    url: "/assets/images/png/Mouse.png",
    fullUrl: "/assets/images/jpg/Mouse.jpg",
    cols: 2,
    rows: 2,
    itemIndex: 12,
  },

  {
    title: "Pansy",
    url: "/assets/images/png/Pansy.png",
    fullUrl: "/assets/images/jpg/Pansy.jpg",
    cols: 3,
    rows: 2,
    itemIndex: 13,
  },

  {
    title: "Pomegranate Spider",
    url: "/assets/images/png/PomSpider.png",
    fullUrl: "/assets/images/jpg/PomSpider.jpg",
    cols: 3,
    rows: 3,
    itemIndex: 14,
  },
  {
    title: "XFiles",
    url: "/assets/images/png/XFiles.png",
    fullUrl: "/assets/images/jpg/XFiles.jpg",
    cols: 3,
    rows: 4,
    itemIndex: 15,
  },
  {
    title: "Autumnal Equinox",
    url: "/assets/images/png/AutumnalEquinox.png",
    fullUrl: "/assets/images/jpg/AutumnalEquinox.jpg",
    cols: 4,
    rows: 3,
    itemIndex: 16,
  },
  {
    title: "Witch Toad",
    url: "/assets/images/png/WitchToad.png",
    fullUrl: "/assets/images/jpg/WitchToad.jpg",
    cols: 5,
    rows: 4,
    itemIndex: 17,
  },
  {
    title: "Pumpkin & Friend",
    url: "/assets/images/png/Pumpkin.png",
    fullUrl: "/assets/images/jpg/Pumpkin.jpg",
    cols: 4,
    rows: 3,
    itemIndex: 18,
  },
  {
    title: "Tree Frog and Mushrooms",
    url: "/assets/images/png/TreeFrog.png",
    fullUrl: "/assets/images/jpg/TreeFrog.jpg",
    cols: 3,
    rows: 2,
    itemIndex: 19,
  },
  {
    title: "blank",
    url: null,
    fullUrl: null,
    cols: 1,
    rows: 1,
  },
  {
    title: "Peony",
    url: "/assets/images/png/Peony.png",
    fullUrl: "/assets/images/jpg/Peony.jpg",
    cols: 4,
    rows: 2,
    itemIndex: 20,
  },
  {
    title: "Dangerous",
    url: "/assets/images/png/Dangerous.png",
    fullUrl: "/assets/images/jpg/Dangerous.jpg",
    cols: 5,
    rows: 3,
    itemIndex: 21,
  },

  {
    title: "Fawn",
    url: "/assets/images/png/Fawn.png",
    fullUrl: "/assets/images/jpg/Fawn.jpg",
    cols: 3,
    rows: 3,
    itemIndex: 22,
  },

  {
    title: "The Head",
    url: "/assets/images/png/TheHead.png",
    fullUrl: "/assets/images/jpg/TheHead.jpg",
    cols: 4,
    rows: 3,
    itemIndex: 23,
  },
  {
    title: "Medusa Antoinette",
    url: "/assets/images/png/Medusa.png",
    fullUrl: "/assets/images/jpg/Medusa.jpg",
    cols: 4,
    rows: 3,
    itemIndex: 24,
  },
  {
    title: "Greif & Growth",
    url: "/assets/images/png/GreifGrowth.png",
    fullUrl: "/assets/images/jpg/GreifGrowth.jpg",
    cols: 4,
    rows: 3,
    itemIndex: 25,
  },
  {
    title: "Fire",
    url: "/assets/images/png/Fire.png",
    fullUrl: "/assets/images/jpg/Fire.jpg",
    cols: 4,
    rows: 4,
    itemIndex: 26,
  },
  {
    title: "The Chase",
    url: "/assets/images/png/TheChase.png",
    fullUrl: "/assets/images/jpg/TheChase.jpg",
    cols: 6,
    rows: 4,
    itemIndex: 27,
  },
  {
    title: "Rose",
    url: "/assets/images/png/Rose.png",
    fullUrl: "/assets/images/jpg/Rose.jpg",
    cols: 2,
    rows: 2,
    itemIndex: 28,
  },
  {
    title: "blank",
    url: null,
    fullUrl: null,
    cols: 1,
    rows: 2,
  },
  {
    title: "Fairy Ring",
    url: "/assets/images/png/FairyRing.png",
    fullUrl: "/assets/images/jpg/FairyRing.jpg",
    cols: 5,
    rows: 4,
    itemIndex: 29,
  },
  {
    title: "Oarfish",
    url: "/assets/images/png/Oarfish.png",
    fullUrl: "/assets/images/jpg/Oarfish.jpg",
    cols: 3,
    rows: 4,
    itemIndex: 30,
  },
  {
    title: "Spicy",
    url: "/assets/images/png/Spicy.png",
    fullUrl: "/assets/images/jpg/Spicy.jpg",
    cols: 4,
    rows: 4,
    itemIndex: 31,
  },
  {
    title: "Art Nouveau Flower1",
    url: "/assets/images/png/ArtNouveauFlower1.png",
    fullUrl: "/assets/images/jpg/ArtNouveauFlower1.jpg",
    cols: 2,
    rows: 2,
    itemIndex: 32,
  },
  {
    title: "Art Nouveau Flower2",
    url: "/assets/images/png/ArtNouveauFlower2.png",
    fullUrl: "/assets/images/jpg/ArtNouveauFlower2.jpg",
    cols: 2,
    rows: 2,
    itemIndex: 33,
  },
  {
    title: "Handurian White Bat",
    url: "/assets/images/png/Bats.png",
    fullUrl: "/assets/images/jpg/Bats.jpg",
    cols: 6,
    rows: 2,
    itemIndex: 34,
  },
  {
    title: "blank",
    url: null,
    fullUrl: null,
    cols: 1,
    rows: 2,
  },
  {
    title: "Art Nouveau Flower3",
    url: "/assets/images/png/ArtNouveauFlower3.png",
    fullUrl: "/assets/images/jpg/ArtNouveauFlower3.jpg",
    cols: 2,
    rows: 2,
    itemIndex: 35,
  },
  {
    title: "Art Nouveau Flower4",
    url: "/assets/images/png/ArtNouveauFlower4.png",
    fullUrl: "/assets/images/jpg/ArtNouveauFlower4.jpg",
    cols: 2,
    rows: 2,
    itemIndex: 36,
  },
  {
    title: "Mushroom 1",
    url: "/assets/images/png/Mushroom1.png",
    fullUrl: "/assets/images/jpg/Mushroom1.jpg",
    cols: 3,
    rows: 2,
    itemIndex: 37,
  },
  {
    title: "Mushroom 2",
    url: "/assets/images/png/Mushroom2.png",
    fullUrl: "/assets/images/jpg/Mushroom2.jpg",
    cols: 3,
    rows: 2,
    itemIndex: 38,
  },

  {
    title: "Spiders",
    url: "/assets/images/png/Spiders.png",
    fullUrl: "/assets/images/jpg/Spiders.jpg",
    cols: 6,
    rows: 4,
    itemIndex: 39,
  },
  {
    title: "blank",
    url: null,
    fullUrl: null,
    cols: 2,
    rows: 2,
  },
  {
    title: "Mushroom 3",
    url: "/assets/images/png/Mushroom3.png",
    fullUrl: "/assets/images/jpg/Mushroom3.jpg",
    cols: 3,
    rows: 2,
    itemIndex: 40,
  },
  {
    title: "blank",
    url: null,
    fullUrl: null,
    cols: 1,
    rows: 2,
  },
  {
    title: "Fig & Paloma",
    url: "/assets/images/png/FigPaloma.png",
    fullUrl: "/assets/images/jpg/FigPaloma.jpg",
    cols: 12,
    rows: 4,
    itemIndex: 41,
  },
];
